{
 "title": "Current Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature °C",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ntemperature\nFROM events\nORDER by id desc\nLIMIT 0,1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nhumidity\nFROM events\nORDER by id desc\nLIMIT 0,1\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\npressure\nFROM events\nORDER by id desc\nLIMIT 0,1\n"
    }
   ]
  },
  {
   "title": "Supply Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nbus_voltage\nFROM events\nORDER by id desc\nLIMIT 0,1\n"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nbus_current\nFROM events\nORDER by id desc\nLIMIT 0,1\n"
    }
   ]
  },
  {
   "title": "Power Output",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\npower\nFROM events\nORDER by id desc\nLIMIT 0,1\n"
    }
   ]
  }
 ]
}